"""Run the SAM 3 vision encoder and save analogous input/output for bioimageio tests.

Produces the ``test_input.npy`` / ``test_output.npy`` pair referenced by
``bioimageio_export.py``:

* ``test_input.npy``  – a raw RGB crop resized to 1008x1008, laid out as
  ``(batch, channel, y, x)`` float32 in the [0, 255] range. The bioimage.io
  preprocessing (``scale_linear`` 1/255 + fixed ImageNet mean/std) turns this
  into the tensor the encoder actually sees.
* ``test_output.npy`` – the ``vision_features`` map the bundled
  ``Sam3EncoderBioImageIO`` produces for that input, ``(batch, 256, 72, 72)``
  float32.

The output is generated by running the *same* bundled wrapper the bioimage.io
model uses, on the *same* ImageNet-normalised input, so the exported package is
reproducible (up to the BFloat16 tolerance set in ``bioimageio_export.py``).
"""

import argparse
import os
from pathlib import Path

import imageio.v3 as imageio
import numpy as np
import torch

from sam3_encoder_bioimageio import Sam3EncoderBioImageIO

# SAM 3 was trained at 1008x1008 (patch size 14 -> 72x72 feature grid).
# ImageNet normalisation is applied inside Sam3EncoderBioImageIO.forward.
IMG_SIZE = 1008

# Cached HuggingFace `facebook/sam3` checkpoint (gated: needs prior `hf auth login`).
DEFAULT_CKPT = os.path.expanduser(
    "~/.cache/huggingface/hub/models--facebook--sam3/snapshots/"
    "3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt"
)


def resize_to_square(img: np.ndarray, size: int) -> np.ndarray:
    """Center-crop to square then resize to (size, size) with PIL bilinear."""
    from PIL import Image

    pil = Image.fromarray(img).convert("RGB")
    w, h = pil.size
    side = min(w, h)
    left, top = (w - side) // 2, (h - side) // 2
    pil = pil.crop((left, top, left + side, top + side)).resize(
        (size, size), Image.BILINEAR
    )
    return np.asarray(pil)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkpoint", default=DEFAULT_CKPT, help="SAM 3 .pt checkpoint")
    parser.add_argument("--image", default="sample_input.png", help="input RGB image")
    args = parser.parse_args()

    os.chdir(Path(__file__).parent)
    Path("output").mkdir(exist_ok=True)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # --- raw input tensor (B, C, y, x), [0, 255] float32 -------------------
    rgb = resize_to_square(imageio.imread(args.image), IMG_SIZE)  # (H, W, 3) uint8
    input_array = rgb.transpose(2, 0, 1)[None].astype(np.float32)  # (1, 3, H, W)
    print("test input:", input_array.shape, input_array.dtype)
    np.save("output/test_input.npy", input_array)

    # Feed the raw [0, 255] tensor straight to the wrapper — it scales to [0, 1]
    # and applies ImageNet mean/std internally (see Sam3EncoderBioImageIO.forward),
    # exactly as bioimage.io will at validation time.
    x = torch.from_numpy(input_array).to(device)

    # --- run the bundled encoder wrapper -----------------------------------
    print(f"Loading SAM 3 encoder and checkpoint: {args.checkpoint}")
    model = Sam3EncoderBioImageIO().to(device).eval()
    state_dict = torch.load(args.checkpoint, map_location="cpu", weights_only=True)
    model.load_state_dict(state_dict)

    with torch.no_grad():
        vision_features = model(x)

    out = vision_features.detach().float().cpu().numpy()
    print("test output (vision_features):", out.shape, out.dtype)
    np.save("output/test_output.npy", out)
    print("Saved output/test_input.npy and output/test_output.npy")


if __name__ == "__main__":
    main()
