{% set pyproject = load_file_data('pyproject.toml') %}
{% set version_match = load_file_regex(
  load_file="src/bioimageio/core/__init__.py",
  regex_pattern='__version__ = "(.+)"') %}
{% set version = version_match[1] %}


package:
  name: {{ pyproject['project']['name'] }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  entry_points:
    {% for ep in setup_py_data['entry_points']['console_scripts'] %}
    - {{ ep }}
    {% endfor %}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{ pyproject['project']['requires-python'] }}
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python >=3.9,<3.13
    {% for dep in setup_py_data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run_constrained:
    - cudatoolkit>=10.1
    {% for dep in setup_py_data['extras_require']['pytorch'] %}
      {% if dep.startswith('torch>=') %}  # pip: torch  -> conda: pytorch
    - py{{ dep.lower() }}
      {% else %}
    - {{ dep.lower() }}
      {% endif %}
    {% endfor %}
    {% for dep in setup_py_data['extras_require']['onnx'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in setup_py_data['extras_require']['tensorflow'] %}
    - {{ dep.lower() }}
    {% endfor %}


test:
  imports:
    - bioimageio.core
  source_files:
    - tests
  requires:
    {% for dep in setup_py_data['extras_require']['dev'] %}
      {% if dep.startswith('torch>=') %}  # pip: torch  -> conda: pytorch
    - py{{ dep.lower() }}
      {% else %}
    - {{ dep.lower() }}
      {% endif %}
    {% endfor %}
  commands:
    - pytest


about:
  home: https://github.com/bioimage-io/core-bioimage-io-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Tools for running BioimageIO compliant neural networks in Python.'
  doc_url: https://github.com/bioimage-io/core-bioimage-io-python
  dev_url: https://github.com/bioimage-io/core-bioimage-io-python
