{% set pyproject = load_file_data('pyproject.toml') %}
{% set version_match = load_file_regex(
  load_file="src/bioimageio/core/__init__.py",
  regex_pattern='__version__ = "(.+)"') %}
{% set version = version_match[1] %}


package:
  name: {{ pyproject['project']['name'] }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  entry_points:
    - bioimageio = {{ pyproject['project']['scripts']['bioimageio'] }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python {{ pyproject['project']['requires-python'] }}
    {% for dep in pyproject['build-system']['requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python {{ pyproject['project']['requires-python'] }}
    {% for dep in pyproject['project']['dependencies'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run_constrained:
    - cudatoolkit>=10.1
    {% for dep in pyproject['project']['optional-dependencies']['pytorch']%}
      {% if dep.startswith('torch>=') %}  # pip: torch  -> conda: pytorch
    - py{{ dep.lower() }}
      {% else %}
    - {{ dep.lower() }}
      {% endif %}
    {% endfor %}
    {% for dep in pyproject['project']['optional-dependencies']['onnx'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in pyproject['project']['optional-dependencies']['tensorflow'] %}
    - {{ dep.lower() }}
    {% endfor %}


test:
  imports:
    - {{ pyproject['project']['name'] }}
  source_files:
    - tests
  requires:
    {% for dep in pyproject['project']['optional-dependencies']['dev'] %}
      {% if dep.startswith('torch>=') %}  # pip: torch  -> conda: pytorch
    - py{{ dep.lower() }}
      {% else %}
    - {{ dep.lower().replace('_', '-') }}
      {% endif %}
    {% endfor %}
  commands:
    - pytest --capture=no


about:
  home: https://github.com/bioimage-io/core-bioimage-io-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Tools for running BioimageIO compliant neural networks in Python.'
  doc_url: https://github.com/bioimage-io/core-bioimage-io-python
  dev_url: https://github.com/bioimage-io/core-bioimage-io-python
